# Generated by Django 2.0.1 on 2018-01-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('project_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
