# Generated by Django 2.0.1 on 2018-01-22 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import js_project.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('js_project', '0002_auto_20180119_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=js_project.models.user_path)),
                ('thumname_image', models.ImageField(upload_to='')),
                ('comment', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
