# Generated by Django 2.0.1 on 2018-01-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_project', '0003_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumname_image',
        ),
        migrations.AddField(
            model_name='photo',
            name='thumnail_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
