# Generated by Django 2.0.1 on 2018-01-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_project', '0005_auto_20180122_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail_image',
        ),
        migrations.AddField(
            model_name='photo',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
