# Generated by Django 2.0.1 on 2018-01-25 07:16

from django.db import migrations
import js_project.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_project', '0006_auto_20180123_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=js_project.models.user_path),
        ),
    ]
