# Generated by Django 2.0.1 on 2018-01-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_project', '0010_auto_20180125_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='explanation',
            field=models.CharField(default='', max_length=255),
        ),
    ]
