# Generated by Django 2.0.1 on 2018-01-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('js_project', '0011_photo_explanation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='explanation',
            new_name='title',
        ),
    ]
